### ISSUE TITLE
Like button not working for posts after the first post

### ISSUE THREAD

**Issue by kkhushie** [Khushi-digi/instagram-clone#1]
I'm having an issue with my Instagram clone. I'm able to like the first post, but I'm not able to like any other posts. I've checked the code and I can't see any obvious errors.

Here are the steps I'm taking:

I go to the home page of my Instagram clone.
I see a list of posts.
I click on the heart icon to like the first post.
The post is liked.
I click on the heart icon to like another post.
Nothing happens.
I've tried refreshing the page, but the issue persists.

![Screenshot 2023-07-13 100412](https://github.com/Khushi-digi/instagram-clone/assets/111669586/9e0d626c-92ed-4862-b8e2-2ae6d1a822f0)

Can you please help me fix this issue?

**Comment by Vinay94278** [comment]
Hello @Khushi-digi I Can Solve this Error Can you please assign it to me.

**Comment by Vinay94278** [comment]
Hello @Khushi-digi  I have solved this error and Also created pull request #2 can please review it and merge it.
